---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-nginx_app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx_app
  template:
    metadata:
      labels:
        app: nginx_app
    spec:
      containers:
      - image: nginx:1.8
        name: nginx_app
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: nginx_app
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: nginx_app

