---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-myapp1
  namespace: myapp1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - image: nginx:1.8
        name: myapp1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp1
  namespace: myapp1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: myapp1

---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp1

